name: Deploy Portfolio Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AKIAR32F6G4QDWR5ORGI }}
          aws-secret-access-key: ${{ secrets.b/ttadzK6aj2F/4dwx9S6RPwSKmhjV+9RWrc092S }}
          aws-region: eu-west-2

      - name: Upload files to S3
        run: aws s3 sync . s3://amz-bucket-230603 --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E3592O0641TLX4 --paths "/*"